remote_theme: poole/hyde

# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
title:            Gu√≠a de exploits
#tagline:          'A Jekyll theme'
#description:      'Basada en Insecure programming de <a href="">Gera</a>'
url:               https://fundacion-sadosky.github.io
baseurl:           /guia-escritura-exploits/

plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled:     true
#  collections: true

#collections:
#  buffer-overflow
#    output: true

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
repo: https://github.com/poole/hyde
